name: ci/cd pipeline

on:
  push:
    branches:
      - "main"
    paths:
      - "src/dotnet/**"
      - "src/terraform/**"
      - ".github/workflows/**"

env:
  TERRAFORM_WORKING_DIRECTORY: src/terraform
  DOTNET_WORKING_DIRECTORY: src/dotnet/AZ-Fn-Graph
  DOTNET_VERSION: "8.0"

  APPLICATION_NAME: "aztf-graph"
  ENVIRONMENT_NAME: "test"

jobs:
  build:
    runs-on: ubuntu-latest

    
  